[colors]
[colors.bright]
black = "#32302f"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"

[colors.normal]
black = "#32302f"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[font]
size = 24.0
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

[window]
decorations = "None"
opacity = 0.95

