require('settings')
require('plugins')
require('mappings')

require('config.telescope')
require('config.autopairs')
require('config.nvimtree')
require('config.gitsigns')
require('config.lualine')
require('config.lspconfig')
require('config.cmp')
