return require("packer").startup(function(use)
	use("wbthomason/packer.nvim")
	use("nvim-lua/plenary.nvim")
	use("nvim-telescope/telescope.nvim")
	use("kyazdani42/nvim-tree.lua")
	use("nvim-lualine/lualine.nvim")
	use("windwp/nvim-autopairs")
	use("mhartington/formatter.nvim")
	use("neovim/nvim-lspconfig")
end)
